# This is a basic workflow to help you get started with Actions

name: TestWorkflowGithub

# Controls when the workflow will run
on:
  push:
    branches: '*'

jobs:
  build-pdf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: 'Build PDF'
        uses: thesis/asciidoctor-action@v1
        with:
          files: doc/index.adoc
