name: asciidoctor action
  # You may pin to the exact commit or the version.
  # uses: Ackee-Blockchain/asciidoctor-action@61aab9d49b28b8615da78a5836929c5eef8da9ee
  uses: Ackee-Blockchain/asciidoctor-action@v1.16
  with:
    # asciidoctor 
    program: asciidoctor -D doc --backend=pdf -o t2v_mod.pdf doc/index.adoc
          
