# This is a basic workflow to help you get started with Actions

name: TestWorkflowGithub

# Controls when the workflow will run
on:
  push:
    branches: '*'

jobs:
  build-pdf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: 'Build Doc'
        uses: thesis/asciidoctor-action@v1
        with:
          files: doc/index.adoc

      - name: Export Artifact
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: /github/workspace/asciidoc-out/doc/
